"""Especificação dos fluxos de algoritmo de cada projeto do portfólio.

Cada fluxo é uma lista de NÓS (ids únicos). As arestas são atributos:
  - next : id do próximo nó (process/start/end/io)
  - yes / no : ids dos próximos nós (decision)

Renderizado em SVG estático pelo `algo.py`. Nada é executado no site.
"""

from projview.algo import Step


def S(id, type, label, **kw):
    return Step(id=id, type=type, label=label, **kw)


ALGORITHMS: dict[str, list[Step]] = {
    "log-forensics": [
        S("s", "start", "Ler log de auth (arquivo/stdin)"),
        S("p", "process", "Iterar linhas; regex em Failed password / Accepted", next="a"),
        S("a", "decision", "É falha de senha?", yes="p2", no="e"),
        S("p2", "process", "Agregar por IP (contador + usuários)", next="c"),
        S("c", "decision", "Mesmo IP em >N usuários?", yes="d", no="e"),
        S("d", "process", "Marcar como user-scanning", next="e"),
        S("e", "process", "Gerar relatório: IP, contagem, indicadores", next="f"),
        S("f", "end", "Imprimir estatísticas por IP"),
    ],
    "cve-watch": [
        S("s", "start", "Ler inventário (software + versão)"),
        S("p", "process", "Ler base local de CVEs", next="a"),
        S("a", "decision", "CVE casa nome+versão?", yes="b", no="c"),
        S("b", "process", "Registrar item vulnerável + severidade", next="c"),
        S("c", "process", "Próximo item do inventário", next="a2"),
        S("a2", "decision", "Fim do inventário?", yes="d", no="a"),
        S("d", "end", "Listar itens vulneráveis"),
    ],
    "pwned-check": [
        S("s", "start", "Receber senha"),
        S("p", "process", "SHA-1 da senha", next="q"),
        S("q", "process", "Enviar só 5 primeiros hex (k-anonymity)", next="a"),
        S("a", "decision", "Prefixo aparece na HIBP?", yes="b", no="e"),
        S("b", "process", "Buscar suffix no range retornado", next="c"),
        S("c", "decision", "Hash completo confere?", yes="d", no="e"),
        S("d", "process", "Reportar quantas vezes vazou", next="e"),
        S("e", "end", "Senha comprometida / segura"),
    ],
    "subdomain-recon": [
        S("s", "start", "Domínio alvo (próprio/autorizado)"),
        S("p", "process", "Consultar crt.sh (certificados TLS)", next="a"),
        S("a", "decision", "Há subdomínios?", yes="b", no="e"),
        S("b", "process", "Resolver DNS de cada um", next="c"),
        S("c", "decision", "Resolve?", yes="d", no="e"),
        S("d", "process", "Adicionar à lista de superfície", next="e"),
        S("e", "end", "Relatório de subdomínios"),
    ],
    "file-integrity-monitor": [
        S("s", "start", "Comando: baseline ou check", next="a"),
        S("a", "decision", "Modo baseline?", yes="b", no="d"),
        S("b", "process", "Calcular SHA-256 de cada arquivo", next="c"),
        S("c", "process", "Salvar baseline.json", next="e"),
        S("d", "process", "Recalcular hashes atuais", next="f"),
        S("f", "process", "Comparar com baseline (added/changed/removed)", next="e"),
        S("e", "end", "Baseline criado / Relatório de integridade"),
    ],
    "tls-auditor": [
        S("s", "start", "host:porta"),
        S("p", "process", "Abrir conexão SSL/TLS", next="a"),
        S("a", "decision", "Conectou?", yes="b", no="f"),
        S("b", "process", "Listar protocolos e ciphers negociados", next="c"),
        S("c", "decision", "Há protocolo/cifra fraca?", yes="d", no="e"),
        S("d", "process", "Sinalizar SSLv3/TLS1.0/1.1, NULL/EXPORT", next="e"),
        S("e", "process", "Verificar validade do certificado", next="f"),
        S("f", "end", "Relatório de configuração TLS"),
    ],
    "pentest-agent": [
        S("s", "start", "Alvo + --authorize", next="a"),
        S("a", "decision", "Alvo na allowlist?", yes="b", no="x"),
        S("x", "end", "Recusado: fora da allowlist"),
        S("b", "process", "Decidir próximo passo de recon (LLM)", next="c"),
        S("c", "decision", "Atingiu max-steps?", yes="e", no="d"),
        S("d", "process", "Executar recon não destrutivo", next="b"),
        S("e", "process", "Gerar relatório", next="f"),
        S("f", "end", "Entregar relatório ao dono"),
    ],
    "honeypot": [
        S("s", "start", "Iniciar SSH/HTTP falsos", next="a"),
        S("a", "decision", "Conexão recebida?", yes="b", no="f"),
        S("b", "process", "Registrar IP, credencial, User-Agent", next="c"),
        S("c", "process", "Persistir em SQLite", next="d"),
        S("d", "decision", "Comando --stats?", yes="e", no="f"),
        S("e", "process", "Aggregar estatísticas", next="f"),
        S("f", "end", "Responder falso / Mostrar stats"),
    ],
    "host-ids": [
        S("s", "start", "Varredura de baseline (--once)", next="a"),
        S("a", "decision", "Modo baseline?", yes="b", no="c"),
        S("b", "process", "Snapshot de processos/conexões/arquivos", next="f"),
        S("c", "process", "Nova varredura periódica", next="d"),
        S("d", "decision", "Mudança vs baseline?", yes="e", no="c"),
        S("e", "process", "Emitir alerta", next="c"),
        S("f", "end", "Baseline pronto / Monitor ativo"),
    ],
    "phishing-detector": [
        S("s", "start", "URL de entrada", next="p"),
        S("p", "process", "Heurísticas: homografos, @, IP, hunches", next="a"),
        S("a", "decision", "Flag --network?", yes="b", no="c"),
        S("b", "process", "Checar certificado SSL/WHOIS", next="c"),
        S("c", "process", "Pontuar risco 0-100", next="d"),
        S("d", "decision", "Score alto?", yes="e", no="f"),
        S("e", "process", "Marcar como suspeito", next="f"),
        S("f", "end", "Resultado + recomendação"),
    ],
    "password-auditor": [
        S("s", "start", "Senha (arg ou oculto)", next="p"),
        S("p", "process", "Calcular entropia (Shannon)", next="a"),
        S("a", "decision", "Em wordlist comum?", yes="b", no="c"),
        S("b", "process", "Marcar senha vazada/comum", next="c"),
        S("c", "process", "Estimar tempo de quebra (ataque)", next="d"),
        S("d", "process", "Detectar sequências/teclado/reuso", next="e"),
        S("e", "end", "Relatório de qualidade + sugestão"),
    ],
    "malware-analyzer": [
        S("s", "start", "Arquivo suspeito", next="p"),
        S("p", "process", "Hashes (MD5/SHA1/SHA256)", next="a"),
        S("a", "decision", "Entropia alta?", yes="b", no="c"),
        S("b", "process", "Suspeitar de packing", next="c"),
        S("c", "process", "Extrair strings + IOCs (URL/IP/domínio)", next="d"),
        S("d", "process", "Matching APIs do Windows suspeitas", next="e"),
        S("e", "process", "Pontuar risco", next="f"),
        S("f", "end", "Relatório estático (sem execução)"),
    ],
    "network-scanner": [
        S("s", "start", "Alvo (IP/CIDR/host)", next="p"),
        S("p", "process", "Descoberta de hosts (nmap ou socket)", next="a"),
        S("a", "decision", "Host ativo?", yes="b", no="f"),
        S("b", "process", "Varrer portas + serviços", next="c"),
        S("c", "decision", "SO detectável?", yes="d", no="e"),
        S("d", "process", "Inferir SO / banner", next="e"),
        S("e", "process", "Salvar em SQLite + gerar HTML", next="f"),
        S("f", "end", "Relatório de varredura"),
    ],
    "threat-intel": [
        S("s", "start", "Comando: add/lookup/search/import/serve", next="a"),
        S("a", "decision", "É ingestão?", yes="b", no="d"),
        S("b", "process", "Detectar tipo (ip/domain/url/hash) + confiança", next="c"),
        S("c", "process", "Armazenar em SQLite", next="f"),
        S("d", "decision", "É consulta?", yes="e", no="g"),
        S("e", "process", "Filtrar por tipo/confiança/tags", next="f"),
        S("f", "decision", "Modo serve?", yes="g", no="h"),
        S("g", "process", "Subir API REST (stdlib)", next="h"),
        S("h", "end", "IOC registrado / resposta da busca"),
    ],
    "mini-siem": [
        S("s", "start", "Ingestão de log (arquivo/stdin)", next="p"),
        S("p", "process", "Parsers por tipo (ssh/web)", next="a"),
        S("a", "decision", "Parseou?", yes="b", no="f"),
        S("b", "process", "Normalizar em evento estruturado", next="c"),
        S("c", "process", "Armazenar em SQLite", next="d"),
        S("d", "decision", "Regra de correlação bate?", yes="e", no="f"),
        S("e", "process", "Disparar alerta (brute-force/web scan)", next="f"),
        S("f", "end", "Query/stats/alertas disponíveis"),
    ],
    "dockview": [
        S("s", "start", "Abrir dockview", next="p"),
        S("p", "process", "Tela da baleia (ENTER)", next="a"),
        S("a", "decision", "Aba selecionada?", yes="b", no="f"),
        S("b", "process", "Consultar recurso Docker", next="c"),
        S("c", "process", "Renderizar tabela na aba", next="d"),
        S("d", "decision", "Tecla de ação (s/x/d/l)?", yes="e", no="f"),
        S("e", "process", "start/stop/remove/log via docker SDK", next="c"),
        S("f", "end", "Painel atualizado"),
    ],
    "DDfetch": [
        S("s", "start", "Executar ddfetch", next="p"),
        S("p", "process", "Ler /etc/os-release, memória, CPU, tema", next="a"),
        S("a", "decision", "Tem ASCII custom?", yes="b", no="c"),
        S("b", "process", "Carregar arte customizada", next="c"),
        S("c", "process", "Montar layout lado a lado", next="d"),
        S("d", "end", "Imprimir fetch no terminal"),
    ],
    "BIGMAN": [
        S("s", "start", "Cliente manda msg no WhatsApp", next="p"),
        S("p", "process", "Webhook valida assinatura", next="a"),
        S("a", "decision", "Válido?", yes="b", no="x"),
        S("x", "end", "Ignorar (assinatura inválida)"),
        S("b", "process", "Gemini gera resposta contextual", next="c"),
        S("c", "process", "Persistir em Supabase", next="d"),
        S("d", "end", "Responder cliente no WhatsApp"),
    ],
    "Umbra": [
        S("s", "start", "JSON de entrada", next="p"),
        S("p", "process", "Detectar campos sensíveis (regex/ML leve)", next="a"),
        S("a", "decision", "Campo sensível?", yes="b", no="c"),
        S("b", "process", "Anonimizar (mascarar/hash)", next="c"),
        S("c", "process", "Reconstruir JSON preservando estrutura", next="d"),
        S("d", "end", "JSON anonimizado (privacidade ética)"),
    ],
    "warden-codec": [
        S("s", "start", "Entrada: texto + esquema (base64/hex/url)"),
        S("p", "process", "Codificar ou decodificar conforme esquema", next="a"),
        S("a", "decision", "Modo decode?", yes="b", no="c"),
        S("b", "process", "Reverter encoding (seguro p/ analise)", next="d"),
        S("c", "process", "Aplicar encoding (ofuscar payload)", next="d"),
        S("d", "end", "Saida codificada/decodificada"),
    ],
    "b64kit": [
        S("s", "start", "Texto de entrada"),
        S("p", "process", "java.util.Base64 codificar", next="a"),
        S("a", "decision", "Modo decode?", yes="b", no="c"),
        S("b", "process", "Decodificar para texto", next="c"),
        S("c", "end", "Resultado Base64"),
    ],
    "jurlmask": [
        S("s", "start", "URL/payload"),
        S("p", "process", "Percent-encode caracteres especiais", next="a"),
        S("a", "decision", "Dupla codificacao?", yes="b", no="c"),
        S("b", "process", "Aplicar encode novamente (ofuscar)", next="c"),
        S("c", "end", "URL ofuscada (autorizado)"),
    ],
    "hashforge-cli": [
        S("s", "start", "Hash alvo + wordlist"),
        S("p", "process", "Ler proxima palavra da wordlist", next="a"),
        S("a", "decision", "hash(palavra) == alvo?", yes="b", no="c"),
        S("b", "process", "Registrar match + palavra", next="d"),
        S("c", "decision", "Fim da wordlist?", yes="d", no="p"),
        S("d", "end", "Senha encontrada / nao encontrada"),
    ],
    "apibrute": [
        S("s", "start", "Endpoint + usuarios + senhas"),
        S("p", "process", "Montar requisicao com credencial", next="a"),
        S("a", "decision", "Resposta 200/302?", yes="b", no="c"),
        S("b", "process", "Marcar credencial valida", next="d"),
        S("c", "process", "Respeitar taxa (rate-limit) e retry", next="d"),
        S("d", "decision", "Fim da lista?", yes="e", no="p"),
        S("e", "end", "Credenciais validas / nenhuma"),
    ],
    "hashvault": [
        S("s", "start", "Senha (texto)"),
        S("p", "process", "SHA-256 com salt opcional", next="a"),
        S("a", "decision", "Verificar contra hash?", yes="b", no="c"),
        S("b", "process", "Comparar digest", next="c"),
        S("c", "end", "Hash gerado / conferencia"),
    ],
    "jhashcrack": [
        S("s", "start", "Hash MD5 alvo + wordlist"),
        S("p", "process", "Ler palavra; MessageDigest MD5", next="a"),
        S("a", "decision", "digest == alvo?", yes="b", no="c"),
        S("b", "process", "Match encontrado", next="d"),
        S("c", "decision", "Fim?", yes="d", no="p"),
        S("d", "end", "Resultado da forca-bruta autorizada"),
    ],
    "portscope": [
        S("s", "start", "Host alvo (proprio)"),
        S("p", "process", "Varrer fafa de portas TCP", next="a"),
        S("a", "decision", "Porta aberta?", yes="b", no="c"),
        S("b", "process", "Registrar servico + banner", next="c"),
        S("c", "decision", "Fim da fafa?", yes="d", no="p"),
        S("d", "end", "Relatorio de portas abertas"),
    ],
    "jportscan": [
        S("s", "start", "Host + portas"),
        S("p", "process", "Socket connect por porta", next="a"),
        S("a", "decision", "Conectou?", yes="b", no="c"),
        S("b", "process", "Registrar porta aberta", next="c"),
        S("c", "decision", "Proxima porta?", yes="p", no="d"),
        S("d", "end", "Lista de portas abertas"),
    ],
    "subdns-recon": [
        S("s", "start", "Dominio proprio + wordlist"),
        S("p", "process", "Resolver subdominio via DNS", next="a"),
        S("a", "decision", "Resolve (A/CNAME)?", yes="b", no="c"),
        S("b", "process", "Adicionar a superficie", next="c"),
        S("c", "decision", "Fim da wordlist?", yes="d", no="p"),
        S("d", "end", "Subdominios descobertos"),
    ],
    "jsubdomain": [
        S("s", "start", "Dominio alvo (proprio)"),
        S("p", "process", "InetAddress.getByName(sub)", next="a"),
        S("a", "decision", "Resolve?", yes="b", no="c"),
        S("b", "process", "Registrar IP", next="c"),
        S("c", "decision", "Proximo sub?", yes="p", no="d"),
        S("d", "end", "Mapeamento de subdominios"),
    ],
    "jdnslook": [
        S("s", "start", "Nome/host"),
        S("p", "process", "Lookup A / AAAA / MX", next="a"),
        S("a", "decision", "Encontrou registros?", yes="b", no="c"),
        S("b", "process", "Listar registros", next="c"),
        S("c", "end", "Resultado DNS"),
    ],
    "reconmap": [
        S("s", "start", "Dominio proprio"),
        S("p", "process", "Coletar hosts/subdominios", next="a"),
        S("a", "process", "Resolver IPs e servicos", next="b"),
        S("b", "decision", "Porta sensivel?", yes="c", no="d"),
        S("c", "process", "Sinalizar exposicao", next="d"),
        S("d", "end", "Mapa de footprint"),
    ],
    "subdomain-recon": [
        S("s", "start", "Dominio proprio"),
        S("p", "process", "crt.sh (certificados)", next="a"),
        S("a", "decision", "Ha subdominios?", yes="b", no="e"),
        S("b", "process", "Resolver DNS de cada um", next="c"),
        S("c", "decision", "Resolve?", yes="d", no="e"),
        S("d", "process", "Adicionar a lista", next="e"),
        S("e", "end", "Relatorio de subdominios"),
    ],
    "jwtpeek": [
        S("s", "start", "Token JWT"),
        S("p", "process", "Split header.payload.signature", next="a"),
        S("a", "process", "Base64url-decode do payload", next="b"),
        S("b", "decision", "Claims legiveis?", yes="c", no="d"),
        S("c", "process", "Exibir claims (sem quebrar assinatura)", next="d"),
        S("d", "end", "Inspecao de claims"),
    ],
    "jsonmask": [
        S("s", "start", "JSON de entrada"),
        S("p", "process", "Parsear com org.json", next="a"),
        S("a", "decision", "Campo sensivel (cpf/email)?", yes="b", no="c"),
        S("b", "process", "Mascarar/anonimizar", next="c"),
        S("c", "process", "Reconstruir JSON", next="d"),
        S("d", "end", "JSON anonimizado"),
    ],
    "sha-sentinel": [
        S("s", "start", "Comando: baseline ou check"),
        S("p", "process", "Calcular SHA-256 dos arquivos", next="a"),
        S("a", "decision", "Modo baseline?", yes="b", no="c"),
        S("b", "process", "Salvar baseline", next="d"),
        S("c", "process", "Comparar com baseline", next="d"),
        S("d", "end", "Baseline / relatorio de integridade"),
    ],
    "backupseal": [
        S("s", "start", "Backups (arquivos/tar)"),
        S("p", "process", "Calcular hash de cada backup", next="a"),
        S("a", "decision", "Hash confere com o esperado?", yes="b", no="c"),
        S("b", "process", "Marcar integro", next="d"),
        S("c", "process", "Alertar corrupcao", next="d"),
        S("d", "end", "Relatorio de integridade de backups"),
    ],
    "hostwatch": [
        S("s", "start", "Diretorio(s) alvo"),
        S("p", "process", "Ler permissoes/owner de arquivos", next="a"),
        S("a", "decision", "Mudanca vs baseline?", yes="b", no="c"),
        S("b", "process", "Alertar (permissao/owner)", next="c"),
        S("c", "decision", "Proximo arquivo?", yes="p", no="d"),
        S("d", "end", "Auditoria de integridade/permissoes"),
    ],
    "jfilehash": [
        S("s", "start", "Arquivo"),
        S("p", "process", "MessageDigest SHA-256 (stream)", next="a"),
        S("a", "decision", "Mais arquivos?", yes="p", no="b"),
        S("b", "end", "Hash(es) SHA-256"),
    ],
    "http-hardener": [
        S("s", "start", "URL do seu site"),
        S("p", "process", "Requisicao HEAD/GET", next="a"),
        S("a", "decision", "HSTS presente?", yes="b", no="c"),
        S("b", "process", "Checar CSP / X-Frame-Options", next="c"),
        S("c", "decision", "Faltam cabecalhos?", yes="d", no="e"),
        S("d", "process", "Listar cabecalhos ausentes", next="e"),
        S("e", "end", "Relatorio de cabecalhos de seguranca"),
    ],
    "phishscore": [
        S("s", "start", "URL de entrada"),
        S("p", "process", "Heuristicas: homografo, @, IP, palavras", next="a"),
        S("a", "decision", "Flag --network?", yes="b", no="c"),
        S("b", "process", "Checar cert/WHOIS", next="c"),
        S("c", "process", "Pontuar risco 0-100", next="d"),
        S("d", "decision", "Score alto?", yes="e", no="f"),
        S("e", "process", "Marcar suspeito", next="f"),
        S("f", "end", "Pontuacao + recomendacao"),
    ],
    "leakheaders": [
        S("s", "start", "Resposta HTTP / headers"),
        S("p", "process", "Escanear Server/X-Powered-By", next="a"),
        S("a", "decision", "Vaza info de tecnologia?", yes="b", no="c"),
        S("b", "process", "Listar headers sensiveis", next="c"),
        S("c", "end", "Relatorio de vazamento"),
    ],
    "cookieguard": [
        S("s", "start", "Dominio/app"),
        S("p", "process", "Coletar Set-Cookie", next="a"),
        S("a", "decision", "Secure presente?", yes="b", no="c"),
        S("b", "process", "Checar HttpOnly/SameSite", next="c"),
        S("c", "decision", "Faltam flags?", yes="d", no="e"),
        S("d", "process", "Listar cookies frageis", next="e"),
        S("e", "end", "Relatorio de flags de cookie"),
    ],
    "csrfmith": [
        S("s", "start", "Endpoint/alvo proprio"),
        S("p", "process", "Forjar formulario com token", next="a"),
        S("a", "decision", "Token ausente/fraco?", yes="b", no="c"),
        S("b", "process", "Gerar PoC de CSRF", next="c"),
        S("c", "end", "Formulario de teste (autorizado)"),
    ],
    "lfiscope": [
        S("s", "start", "URL do app de teste"),
        S("p", "process", "Injetar traversal (../../, encode)", next="a"),
        S("a", "decision", "Arquivo lido?", yes="b", no="c"),
        S("b", "process", "Confirmar LFI/path-traversal", next="c"),
        S("c", "end", "Relatorio de vulnerabilidade"),
    ],
    "sqlinja": [
        S("s", "start", "Parametro alvo (teste)"),
        S("p", "process", "Forjar payload SQLi (', OR 1=1)", next="a"),
        S("a", "decision", "Modo encode?", yes="b", no="c"),
        S("b", "process", "Ofuscar (hex/url)", next="c"),
        S("c", "end", "Payload para teste de input-validation"),
    ],
    "xssmith": [
        S("s", "start", "Contexto alvo (teste)"),
        S("p", "process", "Forjar payload XSS (<script>, event)", next="a"),
        S("a", "decision", "Ofuscar?", yes="b", no="c"),
        S("b", "process", "Encode url/html/hex", next="c"),
        S("c", "end", "Payload para teste de WAF/input"),
    ],
    "wafbypass": [
        S("s", "start", "Vetor de evasao"),
        S("p", "process", "Aplicar tecnica (case/tab/comment)", next="a"),
        S("a", "decision", "Bypassa WAF?", yes="b", no="c"),
        S("b", "process", "Pontuar risco", next="c"),
        S("c", "end", "Classificacao de vetor"),
    ],
    "paramfuzz": [
        S("s", "start", "Endpoint (autorizado)"),
        S("p", "process", "Forjar/ofuscar parametros", next="a"),
        S("a", "decision", "Testar Mass Assignment?", yes="b", no="c"),
        S("b", "process", "Injetar role=admin etc", next="c"),
        S("c", "end", "Parametros de teste"),
    ],
    "openredir": [
        S("s", "start", "URL com redirect"),
        S("p", "process", "Heuristicas: //, dominio estranho", next="a"),
        S("a", "decision", "Redireciona para externo?", yes="b", no="c"),
        S("b", "process", "Pontuar risco de open-redirect", next="c"),
        S("c", "end", "Classificacao de risco"),
    ],
    "headerspoof": [
        S("s", "start", "Servidor proprio"),
        S("p", "process", "Enviar Host/header custom", next="a"),
        S("a", "decision", "Servidor aceita?", yes="b", no="c"),
        S("b", "process", "Relatar comportamento de spoofing", next="c"),
        S("c", "end", "Relatorio de cabecalhos"),
    ],
    "secretlint": [
        S("s", "start", "Diretorio/repo"),
        S("p", "process", "Regex de segredos (API key/token)", next="a"),
        S("a", "decision", "Match encontrado?", yes="b", no="c"),
        S("b", "process", "Listar segredo + linha (mascarado)", next="c"),
        S("c", "decision", "Proximo arquivo?", yes="p", no="d"),
        S("d", "end", "Segredos encontrados"),
    ],
    "phishforge": [
        S("s", "start", "Template de engenharia social"),
        S("p", "process", "Gerar URL de simulacao", next="a"),
        S("a", "process", "Pontuar risco da URL", next="b"),
        S("b", "decision", "Score alto?", yes="c", no="d"),
        S("c", "process", "Marcar como eficaz (lab)", next="d"),
        S("d", "end", "URL de simulacao propria"),
    ],
    "aeslock": [
        S("s", "start", "Texto + chave"),
        S("p", "process", "Cipher AES/CBC (key expandida)", next="a"),
        S("a", "decision", "Modo decrypt?", yes="b", no="c"),
        S("b", "process", "Reverter (demo)", next="c"),
        S("c", "end", "Texto cifrado/claro"),
    ],
    "jrc4stream": [
        S("s", "start", "Dados + chave RC4"),
        S("p", "process", "KSA (init keystream)", next="a"),
        S("a", "process", "PRGA (gerar keystream)", next="b"),
        S("b", "decision", "Mais bytes?", yes="p", no="c"),
        S("c", "end", "Stream cifrado (educacional)"),
    ],
    "cpfvalid": [
        S("s", "start", "CPF/CNPJ/email"),
        S("p", "process", "Validar formato", next="a"),
        S("a", "decision", "Tem digitos verificadores?", yes="b", no="c"),
        S("b", "process", "Conferir digitos", next="c"),
        S("c", "end", "Valido / invalido"),
    ],
    "jcpfcheck": [
        S("s", "start", "CPF (11 digitos)"),
        S("p", "process", "Calcular digitos verificadores", next="a"),
        S("a", "decision", "Confere com informado?", yes="b", no="c"),
        S("b", "process", "Marcar valido", next="c"),
        S("c", "end", "Resultado da validacao"),
    ],
    "authsentry": [
        S("s", "start", "Log de auth (arquivo/stdin)"),
        S("p", "process", "Regex em Failed password", next="a"),
        S("a", "decision", "Falha de senha?", yes="b", no="e"),
        S("b", "process", "Agregar por IP", next="c"),
        S("c", "decision", ">N tentativas?", yes="d", no="e"),
        S("d", "process", "Marcar brute-force", next="e"),
        S("e", "end", "Relatorio de tentativas"),
    ],
    "iochunt": [
        S("s", "start", "Log/relatorio"),
        S("p", "process", "Regex de IP/hash/dominio", next="a"),
        S("a", "decision", "IOC encontrado?", yes="b", no="c"),
        S("b", "process", "Catalogar indicador", next="c"),
        S("c", "decision", "Proxima linha?", yes="p", no="d"),
        S("d", "end", "IOCs coletados"),
    ],
    "pktwatch": [
        S("s", "start", "Dump de trafego (texto)"),
        S("p", "process", "Parser de linhas de pacote", next="a"),
        S("a", "decision", "Padrao suspeito?", yes="b", no="c"),
        S("b", "process", "Marcar (scan/exfil)", next="c"),
        S("c", "decision", "Proximo pacote?", yes="p", no="d"),
        S("d", "end", "Analise de trafego"),
    ],
    "blackview": [
        S("s", "start", "Abrir blackview"),
        S("p", "process", "Sync lista BlackArch (pacman)", next="a"),
        S("a", "decision", "Aba selecionada?", yes="b", no="f"),
        S("b", "process", "Listar ferramentas/categoria", next="c"),
        S("c", "decision", "Tecla 'i' (instalar)?", yes="d", no="e"),
        S("d", "process", "sudo pacman -S (com confirmacao)", next="e"),
        S("e", "decision", "Tecla 'x' (ver --help)?", yes="g", no="f"),
        S("g", "process", "Capturar --help da ferramenta", next="f"),
        S("f", "end", "Painel atualizado"),
    ],
    "gitview": [
        S("s", "start", "Abrir gitview (repo)"),
        S("p", "process", "Tabs: Stage/Files/Branches/Repos/History/PRs", next="a"),
        S("a", "decision", "Aba Stage + space?", yes="b", no="c"),
        S("b", "process", "git add (stage) selecionados", next="c"),
        S("c", "decision", "Commit + push?", yes="d", no="e"),
        S("d", "process", "git commit + git push (upstream)", next="e"),
        S("e", "decision", "Aba Files + 'a'?", yes="g", no="f"),
        S("g", "process", "Copiar arquivo do PC p/ repo (stage)", next="f"),
        S("f", "end", "Repo sincronizado"),
    ],

}
