"""Especificação dos fluxos de algoritmo de cada projeto do portfólio.

Cada fluxo é uma lista de NÓS (ids únicos). As arestas são atributos:
  - next : id do próximo nó (process/start/end/io)
  - yes / no : ids dos próximos nós (decision)

Renderizado em SVG estático pelo `algo.py`. Nada é executado no site.
"""

from projview.algo import Step


def S(id, type, label, **kw):
    return Step(id=id, type=type, label=label, **kw)


ALGORITHMS: dict[str, list[Step]] = {
    "log-forensics": [
        S("s", "start", "Ler log de auth (arquivo/stdin)"),
        S("p", "process", "Iterar linhas; regex em Failed password / Accepted", next="a"),
        S("a", "decision", "É falha de senha?", yes="p2", no="e"),
        S("p2", "process", "Agregar por IP (contador + usuários)", next="c"),
        S("c", "decision", "Mesmo IP em >N usuários?", yes="d", no="e"),
        S("d", "process", "Marcar como user-scanning", next="e"),
        S("e", "process", "Gerar relatório: IP, contagem, indicadores", next="f"),
        S("f", "end", "Imprimir estatísticas por IP"),
    ],
    "cve-watch": [
        S("s", "start", "Ler inventário (software + versão)"),
        S("p", "process", "Ler base local de CVEs", next="a"),
        S("a", "decision", "CVE casa nome+versão?", yes="b", no="c"),
        S("b", "process", "Registrar item vulnerável + severidade", next="c"),
        S("c", "process", "Próximo item do inventário", next="a2"),
        S("a2", "decision", "Fim do inventário?", yes="d", no="a"),
        S("d", "end", "Listar itens vulneráveis"),
    ],
    "pwned-check": [
        S("s", "start", "Receber senha"),
        S("p", "process", "SHA-1 da senha", next="q"),
        S("q", "process", "Enviar só 5 primeiros hex (k-anonymity)", next="a"),
        S("a", "decision", "Prefixo aparece na HIBP?", yes="b", no="e"),
        S("b", "process", "Buscar suffix no range retornado", next="c"),
        S("c", "decision", "Hash completo confere?", yes="d", no="e"),
        S("d", "process", "Reportar quantas vezes vazou", next="e"),
        S("e", "end", "Senha comprometida / segura"),
    ],
    "subdomain-recon": [
        S("s", "start", "Domínio alvo (próprio/autorizado)"),
        S("p", "process", "Consultar crt.sh (certificados TLS)", next="a"),
        S("a", "decision", "Há subdomínios?", yes="b", no="e"),
        S("b", "process", "Resolver DNS de cada um", next="c"),
        S("c", "decision", "Resolve?", yes="d", no="e"),
        S("d", "process", "Adicionar à lista de superfície", next="e"),
        S("e", "end", "Relatório de subdomínios"),
    ],
    "file-integrity-monitor": [
        S("s", "start", "Comando: baseline ou check", next="a"),
        S("a", "decision", "Modo baseline?", yes="b", no="d"),
        S("b", "process", "Calcular SHA-256 de cada arquivo", next="c"),
        S("c", "process", "Salvar baseline.json", next="e"),
        S("d", "process", "Recalcular hashes atuais", next="f"),
        S("f", "process", "Comparar com baseline (added/changed/removed)", next="e"),
        S("e", "end", "Baseline criado / Relatório de integridade"),
    ],
    "tls-auditor": [
        S("s", "start", "host:porta"),
        S("p", "process", "Abrir conexão SSL/TLS", next="a"),
        S("a", "decision", "Conectou?", yes="b", no="f"),
        S("b", "process", "Listar protocolos e ciphers negociados", next="c"),
        S("c", "decision", "Há protocolo/cifra fraca?", yes="d", no="e"),
        S("d", "process", "Sinalizar SSLv3/TLS1.0/1.1, NULL/EXPORT", next="e"),
        S("e", "process", "Verificar validade do certificado", next="f"),
        S("f", "end", "Relatório de configuração TLS"),
    ],
    "pentest-agent": [
        S("s", "start", "Alvo + --authorize", next="a"),
        S("a", "decision", "Alvo na allowlist?", yes="b", no="x"),
        S("x", "end", "Recusado: fora da allowlist"),
        S("b", "process", "Decidir próximo passo de recon (LLM)", next="c"),
        S("c", "decision", "Atingiu max-steps?", yes="e", no="d"),
        S("d", "process", "Executar recon não destrutivo", next="b"),
        S("e", "process", "Gerar relatório", next="f"),
        S("f", "end", "Entregar relatório ao dono"),
    ],
    "honeypot": [
        S("s", "start", "Iniciar SSH/HTTP falsos", next="a"),
        S("a", "decision", "Conexão recebida?", yes="b", no="f"),
        S("b", "process", "Registrar IP, credencial, User-Agent", next="c"),
        S("c", "process", "Persistir em SQLite", next="d"),
        S("d", "decision", "Comando --stats?", yes="e", no="f"),
        S("e", "process", "Aggregar estatísticas", next="f"),
        S("f", "end", "Responder falso / Mostrar stats"),
    ],
    "host-ids": [
        S("s", "start", "Varredura de baseline (--once)", next="a"),
        S("a", "decision", "Modo baseline?", yes="b", no="c"),
        S("b", "process", "Snapshot de processos/conexões/arquivos", next="f"),
        S("c", "process", "Nova varredura periódica", next="d"),
        S("d", "decision", "Mudança vs baseline?", yes="e", no="c"),
        S("e", "process", "Emitir alerta", next="c"),
        S("f", "end", "Baseline pronto / Monitor ativo"),
    ],
    "phishing-detector": [
        S("s", "start", "URL de entrada", next="p"),
        S("p", "process", "Heurísticas: homografos, @, IP, hunches", next="a"),
        S("a", "decision", "Flag --network?", yes="b", no="c"),
        S("b", "process", "Checar certificado SSL/WHOIS", next="c"),
        S("c", "process", "Pontuar risco 0-100", next="d"),
        S("d", "decision", "Score alto?", yes="e", no="f"),
        S("e", "process", "Marcar como suspeito", next="f"),
        S("f", "end", "Resultado + recomendação"),
    ],
    "password-auditor": [
        S("s", "start", "Senha (arg ou oculto)", next="p"),
        S("p", "process", "Calcular entropia (Shannon)", next="a"),
        S("a", "decision", "Em wordlist comum?", yes="b", no="c"),
        S("b", "process", "Marcar senha vazada/comum", next="c"),
        S("c", "process", "Estimar tempo de quebra (ataque)", next="d"),
        S("d", "process", "Detectar sequências/teclado/reuso", next="e"),
        S("e", "end", "Relatório de qualidade + sugestão"),
    ],
    "malware-analyzer": [
        S("s", "start", "Arquivo suspeito", next="p"),
        S("p", "process", "Hashes (MD5/SHA1/SHA256)", next="a"),
        S("a", "decision", "Entropia alta?", yes="b", no="c"),
        S("b", "process", "Suspeitar de packing", next="c"),
        S("c", "process", "Extrair strings + IOCs (URL/IP/domínio)", next="d"),
        S("d", "process", "Matching APIs do Windows suspeitas", next="e"),
        S("e", "process", "Pontuar risco", next="f"),
        S("f", "end", "Relatório estático (sem execução)"),
    ],
    "network-scanner": [
        S("s", "start", "Alvo (IP/CIDR/host)", next="p"),
        S("p", "process", "Descoberta de hosts (nmap ou socket)", next="a"),
        S("a", "decision", "Host ativo?", yes="b", no="f"),
        S("b", "process", "Varrer portas + serviços", next="c"),
        S("c", "decision", "SO detectável?", yes="d", no="e"),
        S("d", "process", "Inferir SO / banner", next="e"),
        S("e", "process", "Salvar em SQLite + gerar HTML", next="f"),
        S("f", "end", "Relatório de varredura"),
    ],
    "threat-intel": [
        S("s", "start", "Comando: add/lookup/search/import/serve", next="a"),
        S("a", "decision", "É ingestão?", yes="b", no="d"),
        S("b", "process", "Detectar tipo (ip/domain/url/hash) + confiança", next="c"),
        S("c", "process", "Armazenar em SQLite", next="f"),
        S("d", "decision", "É consulta?", yes="e", no="g"),
        S("e", "process", "Filtrar por tipo/confiança/tags", next="f"),
        S("f", "decision", "Modo serve?", yes="g", no="h"),
        S("g", "process", "Subir API REST (stdlib)", next="h"),
        S("h", "end", "IOC registrado / resposta da busca"),
    ],
    "mini-siem": [
        S("s", "start", "Ingestão de log (arquivo/stdin)", next="p"),
        S("p", "process", "Parsers por tipo (ssh/web)", next="a"),
        S("a", "decision", "Parseou?", yes="b", no="f"),
        S("b", "process", "Normalizar em evento estruturado", next="c"),
        S("c", "process", "Armazenar em SQLite", next="d"),
        S("d", "decision", "Regra de correlação bate?", yes="e", no="f"),
        S("e", "process", "Disparar alerta (brute-force/web scan)", next="f"),
        S("f", "end", "Query/stats/alertas disponíveis"),
    ],
    "dockview": [
        S("s", "start", "Abrir dockview", next="p"),
        S("p", "process", "Tela da baleia (ENTER)", next="a"),
        S("a", "decision", "Aba selecionada?", yes="b", no="f"),
        S("b", "process", "Consultar recurso Docker", next="c"),
        S("c", "process", "Renderizar tabela na aba", next="d"),
        S("d", "decision", "Tecla de ação (s/x/d/l)?", yes="e", no="f"),
        S("e", "process", "start/stop/remove/log via docker SDK", next="c"),
        S("f", "end", "Painel atualizado"),
    ],
    "DDfetch": [
        S("s", "start", "Executar ddfetch", next="p"),
        S("p", "process", "Ler /etc/os-release, memória, CPU, tema", next="a"),
        S("a", "decision", "Tem ASCII custom?", yes="b", no="c"),
        S("b", "process", "Carregar arte customizada", next="c"),
        S("c", "process", "Montar layout lado a lado", next="d"),
        S("d", "end", "Imprimir fetch no terminal"),
    ],
    "BIGMAN": [
        S("s", "start", "Cliente manda msg no WhatsApp", next="p"),
        S("p", "process", "Webhook valida assinatura", next="a"),
        S("a", "decision", "Válido?", yes="b", no="x"),
        S("x", "end", "Ignorar (assinatura inválida)"),
        S("b", "process", "Gemini gera resposta contextual", next="c"),
        S("c", "process", "Persistir em Supabase", next="d"),
        S("d", "end", "Responder cliente no WhatsApp"),
    ],
    "Umbra": [
        S("s", "start", "JSON de entrada", next="p"),
        S("p", "process", "Detectar campos sensíveis (regex/ML leve)", next="a"),
        S("a", "decision", "Campo sensível?", yes="b", no="c"),
        S("b", "process", "Anonimizar (mascarar/hash)", next="c"),
        S("c", "process", "Reconstruir JSON preservando estrutura", next="d"),
        S("d", "end", "JSON anonimizado (privacidade ética)"),
    ],
}
